select * from VehicleXEmployee; -- Drop VehicleXEmployee table in case it already exists
select * from Employee; -- Drop Employee table in case it already exists
select * from Person; -- Drop Person table in case it already exists
select * from "Location"; -- Drop Location table in case it already exists
select * from City; -- Drop City table in case it already exists
select * from "State"; -- Drop State table in case it already exists
select * from Country; -- Drop Country table in case it already exists
select * from Community; -- Drop Community table in case it already exists
select * from Park; -- Drop Park table in case it already exists
select * from CommunityXPark; -- Drop CommunityXPark table in case it already exists
select * from Area; -- Drop Area table in case it already exists
select * from Vehicle; -- Drop Vehicle table in case it already exists
select * from AssignedArea; -- Drop AssignedArea table in case it already exists
select * from Speciality; -- Drop Speciality table in case it already exists
select * from ResearchProject; -- Drop ResearchProject table in case it already exists
select * from ResearchProjectXEmployee; -- Drop ResearchProjectXEmployee table in case it already exists
select * from Profession; -- Drop Profession table in case it already exists
select * from Accommodation; -- Drop Accommodation table in case it already exists
select * from Visitor; -- Drop Visitor table in case it already exists
select * from Tour; -- Drop Tour table in case it already exists
select * from AccommodationXTour; -- Drop AccommodationXTour table in case it already exists
